name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      # Log in to Docker Hub before building or pushing
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      # Set up Docker Buildx for multi-platform builds
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Build and push the Docker image in a single step
      - name: Build and Push Docker image
        run: |
          docker buildx build --platform linux/amd64 --tag johnnote/sail-8.1:latest --push .

      # Deploy the application to EC2 using SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            echo "Pulling Docker image..."
            docker pull johnnote/sail-8.1:latest
            echo "Navigating to application directory..."
            cd /home/ec2-user/sail-8.1
            echo "Stopping existing containers..."
            docker-compose down
            echo "Starting new containers..."
            docker-compose up -d
            echo "Installing Composer dependencies..."
            docker-compose exec -T app composer install --no-dev --prefer-dist
            echo "Generating application key..."
            docker-compose exec -T app php artisan key:generate
            echo "Running migrations..."
            docker-compose exec -T app php artisan migrate
            echo "Caching configuration..."
            docker-compose exec -T app php artisan config:cache
