name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Deploy the application to EC2 using SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Navigate to a working directory and ensure it's set up
            mkdir -p /home/ec2-user/sail-8.1
            cd /home/ec2-user/sail-8.1
            
            # Clone your repository if needed
            git clone https://github.com/jcrocker-cmd/Crud-Baral.git .
            
            # Build the Docker image
            docker build -t sail-8.1:latest .

            # If Docker Compose is not installed, install it
            sudo curl -L "https://github.com/docker/compose/releases/download/1.29.2/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
            sudo chmod +x /usr/local/bin/docker-compose

            # Use Docker Compose to manage the containers
            docker-compose down
            docker-compose up -d

            # Run the necessary Laravel commands
            docker-compose exec -T app composer install --no-dev --prefer-dist
            docker-compose exec -T app php artisan key:generate
            docker-compose exec -T app php artisan migrate
            docker-compose exec -T app php artisan config:cache
