name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      # Deploy the application to EC2 using SSH
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull johnnote/sail-8.1:latest
            cd /home/ec2-user/sail-8.1
            docker build -t sail-8.1:latest .
            docker-compose down
            docker-compose up -d
            docker-compose exec -T app composer install --no-dev --prefer-dist
            docker-compose exec -T app php artisan key:generate
            docker-compose exec -T app php artisan migrate
            docker-compose exec -T app php artisan config:cache
