name: Deploy Laravel Application

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: docker buildx build --platform linux/amd64 --tag johnnote/crud-baral:latest --push .

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Push Docker image
        run: docker push johnnote/crud-baral:latest

      - name: Generate APP_KEY
        run: |
          docker run --rm -v $(pwd):/var/www/html -w /var/www/html johnnote/crud-baral:latest ./vendor/bin/sail php artisan key:generate

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull johnnote/crud-baral:latest
            cd /home/ec2-user/crud-baral
            docker-compose down
            docker-compose up -d
            ./vendor/bin/sail php artisan migrate
            ./vendor/bin/sail php artisan config:cache
