name: Deploy Docker Container

on:
  push:
    branches:
      - main  # Set this to your deployment branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push Docker image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/your-app-name:latest .
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/your-app-name:latest

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.2.0
        with:
          host: ${{ secrets.EC2_PUBLIC_IP }}
          username: ${{ secrets.EC2_SSH_USERNAME }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            # Update Docker image on EC2
            docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/your-app-name:latest
            docker stop $(docker ps -q --filter ancestor=${{ secrets.DOCKER_HUB_USERNAME }}/your-app-name:latest) || true
            docker run -d -p 80:80 --name your-app-container ${{ secrets.DOCKER_HUB_USERNAME }}/your-app-name:latest
